version: '3'

services:
  jenkins:
    image: wikidata-jenkins:latest
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - wikidata-jenkins-home:/var/jenkins_home

volumes:
  wikidata-jenkins-home: